Prevent `init` subcommand to call useless code

diff --git a/src/gws b/src/gws
--- a/src/gws
+++ b/src/gws
@@ -871,19 +871,19 @@ if [[ "$1" != "init" ]]; then
     # Then read the list of projects and ignore list
     read_projects
     read_ignored
+
+    # Remove ignored projects
+    projects_indexes=( $(remove_matching projects_indexes[@] ignored_patterns[@]) )
+
+    # If a path is specified as second argument, limit projects to the ones matching
+    # the path
+    if [[ -n "$2" ]]; then
+        error_msg="${C_RED}The directory '$2' is not found.${C_OFF}"
+        projects_list=$(keep_prefixed_projects "$2") || (echo -e "$error_msg" && exit 1) || exit 1
+        projects_indexes=( ${projects_list} )
+    fi
 fi
 
-
-# Remove ignored projects
-projects_indexes=( $(remove_matching projects_indexes[@] ignored_patterns[@]) )
-
-# If a path is specified as second argument, limit projects to the ones matching
-# the path
-if [[ -n "$2" ]]; then
-    error_msg="${C_RED}The directory '$2' is not found.${C_OFF}"
-    projects_list=$(keep_prefixed_projects "$2") || (echo -e "$error_msg" && exit 1) || exit 1
-    projects_indexes=( ${projects_list} )
-fi
 
 # Finally select the desired command
 case $1 in
