Allow a second argument to specify a subfolder
Close #14

diff --git a/src/gws b/src/gws
--- a/src/gws
+++ b/src/gws
@@ -198,6 +198,32 @@ function remove_prefixed()
     return 0
 }
 
+# Keep projects that are prefixed by the given directory
+function keep_prefixed_projects()
+{
+    local limit_to dir current
+
+    # First check if the folder exists
+    [[ ! -d "${START_PWD}/$1" ]] && return 1
+
+    # Get the full path to limit to in regexp form
+    limit_to=$(cd "${START_PWD}/$1" && pwd )/
+    limit_to=$(sed -e 's/[]\/()$*.^|[]/\\&/g' <<< "$limit_to")
+
+    # Iterate over each project
+    for dir in "${projects_indexes[@]}"
+    do
+        # Get its full path
+        current=$(cd $dir; pwd)/
+
+        # If it match, add it to the output
+        [[ $current =~ ^$limit_to ]] && echo -n "$dir "
+    done
+
+    # Everything is right
+    return 0
+}
+
 # }}}
 
 # {{{ Projects functions
@@ -813,15 +839,22 @@ function usage()
 {
     echo -e "gws is an helper to manage workspaces which contain git repositories."
     echo -e ""
-    echo -e "Usage: ${C_RED}$(basename "$0")${C_OFF} ${C_BLUE}<command>${C_OFF}"
+    echo -e "Usages: ${C_RED}$(basename "$0")${C_OFF} ${C_BLUE}<command>${C_OFF} [${C_GREEN}<directory>${C_OFF}]"
+    echo -e "        ${C_RED}$(basename "$0")${C_OFF} [${C_GREEN}<directory>${C_OFF}]"
     echo -e ""
-    echo -e "where <command> is:"
+    echo -e "where ${C_BLUE}<command>${C_OFF} is:"
     echo -e "    ${C_BLUE}init${C_OFF}   - Detect the repositories and create the projects list"
     echo -e "    ${C_BLUE}update${C_OFF} - Update the workspace to get new repositories from projects list"
     echo -e "    ${C_BLUE}status${C_OFF} - Print status for all repositories in the workspace"
     echo -e "    ${C_BLUE}fetch${C_OFF}  - Print status for all repositories in the workspace, but fetch the origin before"
     echo -e "    ${C_BLUE}ff${C_OFF}     - Print status for all repositories in the workspace, but fast forward from origin before"
     echo -e "    ${C_BLUE}check${C_OFF}  - Check the workspace for all repositories (known/unknown/missing)"
+    echo -e ""
+    echo -e "If no ${C_BLUE}<command>${C_OFF} is specified, the command ${C_BLUE}status${C_OFF} is assumed."
+    echo -e ""
+    echo -e "where ${C_GREEN}<directory>${C_OFF} can be a path to limit the scope of the commands to a specific subfolder"
+    echo -e "of the workspace."
+    echo -e ""
     exit 1
 }
 
@@ -844,6 +877,14 @@ fi
 # Remove ignored projects
 projects_indexes=( $(remove_matching projects_indexes[@] ignored_patterns[@]) )
 
+# If a path is specified as second argument, limit projects to the ones matching
+# the path
+if [[ -n "$2" ]]; then
+    error_msg="${C_RED}The directory '$2' is not found.${C_OFF}"
+    projects_list=$(keep_prefixed_projects "$2") || (echo -e "$error_msg" && exit 1) || exit 1
+    projects_indexes=( ${projects_list} )
+fi
+
 # Finally select the desired command
 case $1 in
     "init")
@@ -852,7 +893,7 @@ case $1 in
     "update")
         cmd_update
         ;;
-    ""|"status")
+    "status")
         cmd_status $S_NONE
         ;;
     "fetch")
@@ -867,7 +908,17 @@ case $1 in
     "--version"|"-v")
         echo -e "gws version ${C_RED}$VERSION${C_OFF}"
         ;;
-    *) usage ;;
+    "--help"|"-h")
+        usage
+        ;;
+    *)
+        if [[ -n "$1" ]]; then
+            error_msg="${C_RED}The directory '$1' is not found and is not a recognized command.${C_OFF}"
+            projects_list=$(keep_prefixed_projects "$1") || (echo -e "$error_msg" && exit 1) || exit 1
+            projects_indexes=( ${projects_list} )
+        fi
+        cmd_status $S_NONE
+        ;;
 esac
 
 # vim: fdm=marker
